// Example generated by Mahdi Malkawi based on:
// Flow Graph Anomalies: What's in a Loop? by Michael Wolfe
// https://scholararchive.ohsu.edu/downloads/9z903022q?locale=en
// Control Flow Graph 1, (G1:) page 2

int main(int argc, char **argv)
{
    int first = 0;

    loop:
    goto loop;

    return 0;
}