// Example generated by Mahdi Malkawi

int MAX = 100;

int main(int argc, char **argv)
{
    int counter = 0;
    int sum = 0;

    while (counter < MAX)
    {
        sum += counter;
        ++counter;
    }

    return 0;
}