// Example generated by Mahdi Malkawi based on Dr. Martin Nyx Brain's suggestion
    // based on https://www.lysator.liu.se/c/duffs-device.html
void duffs_device(const int count)
{
    int cycles = (count + 7) / 8;
    switch (count % 8)
    {
    case 0:
        do
        {
            printf("Standard Case\n");
        case 7:
            printf("Case 7\n");
        case 6:
            printf("Case 6\n");
        case 5:
            printf("Case 5\n");
        case 4:
            printf("Case 4\n");
        case 3:
            printf("Case 3\n");
        case 2:
            printf("Case 2\n");
        case 1:
            printf("Case 1\n");

        } while (--cycles > 0);
    }
}

int main(int argc, char **argv)
{
    // cycles = 4, so
    // 27 mod 8 = 3
    // Start at case 3, then then go down switch cases, then decrement, cycles = 3,
    // then continue from the top and continue until condition 0 > 0, then stop.
    // In total the do while statement will run 4 times. 3 + (8 * 3) = 27 times.
    duffs_device(27);

    return 0;
}