// Example generated by Mahdi Malkawi based on:
// Flow Graph Anomalies: What's in a Loop? by Michael Wolfe
// https://scholararchive.ohsu.edu/downloads/9z903022q?locale=en
// Control Flow Graph 1, (G1:) page 2

int main(int argc, char **argv)
{
    int a = 1;

l1:
    a = 1+1;

    int b = -1;

l2:
    b += 1;
    if (b > 0)
    {
        goto l1;
    }

    return 0;
}