// Example generated by Mahdi Malkawi based on:
// Flow Graph Anomalies: What's in a Loop? by Michael Wolfe
// https://scholararchive.ohsu.edu/downloads/9z903022q?locale=en
// Control Flow Graph 1, (G1:) page 2

int main(int argc, char **argv)
{
    int a = 1;

l1:
    a += 1;

    if (a == 2)
    {
        goto l3;
    }

    int b = a - 1;

l2:
    if (b > 0)
    {
        goto l2;
    }

l3:

    return 0;
}