// Example generated by Mahdi Malkawi based on Dr. Martin Nyx Brain's suggestion

int MAX = 100;

int main(int argc, char **argv)
{
    int counter = 0;
    int counter2 = 0;
    int sum = 0;

    do
    {
        sum += counter;
        ++counter;

        do
        {
            sum += counter2;
            ++counter2;

        } while (counter2 < MAX);

    } while (counter < MAX);

    return 0;
}