// Example generated by Celina G. Val
// https://github.com/diffblue/cbmc/issues/7506#issue-1557571913

// no_loops.c
int loop_free()
{
bb0:;
    int var_3 = 1;
    goto bb1;

exit:;
    return 10;

bb1:;
    goto exit;
}

int main()
{
    assert(loop_free() == 0);
    return 0;
}