// Example generated by Mahdi Malkawi based on:
// Flow Graph Anomalies: What's in a Loop? by Michael Wolfe
// https://scholararchive.ohsu.edu/downloads/9z903022q?locale=en
// Control Flow Graph 3, (G3:) page 4

int main(int argc, char **argv)
{
    int a = 1;
    int b = 2;
    int error = 0;
l1:
    if (a)
    {
        a + 1;
    }

    int counter = 10;

l2:
    b + 2;

l3:
    if (counter < 10)
    {
        --counter;
    }
    else
    {
        goto l2;
        error = 1;
    }

l4:
    if (error)
    {
        goto l3;
    }
    return 0;
}