// Example generated by Mahdi Malkawi based on:
// Flow Graph Anomalies: What's in a Loop? by Michael Wolfe
// https://scholararchive.ohsu.edu/downloads/9z903022q?locale=en
// Control Flow Graph 5b (G5b:) page 5

int main(int argc, char **argv)
{
    int array[] = {1, 2};
    int length = sizeof(array) / sizeof(array[0]);

    int counter = 0;
    int sum = 0;

l1:

    while (counter < length)
    {
        sum += array[counter];
        ++counter;

        if (sum == 15)
        {
            goto l1;
        }
        else
        {
            break;
        }
    }

    return 0;
}