// Example generated by Mahdi Malkawi based on:
// Flow Graph Anomalies: What's in a Loop? by Michael Wolfe
// https://scholararchive.ohsu.edu/downloads/9z903022q?locale=en
// Control Flow Graph 2, (G2:) page 3

int size_of_something = 100;

int main(int argc, char **argv)
{
        int sum = 0;

        for (int counter = 0; counter < size_of_something; ++counter)
        {
            for (int counter2 = 0; counter2 < size_of_something; ++counter2)
            {
                sum += (counter + counter2);
            }
        }

    return 0;
}