// Example generated by Mahdi Malkawi

int MAX = 100;

int main(int argc, char **argv)
{
    int counter = 0;
    int sum = 0;

    for (int counter = 0; counter < MAX; ++counter)
    {
        sum += counter;
    }

    return 0;
}