// Example generated by Mahdi Malkawi based on:
// Flow Graph Anomalies: What's in a Loop? by Michael Wolfe
// https://scholararchive.ohsu.edu/downloads/9z903022q?locale=en
// Control Flow Graph 3, (G3:) page 4

int main(int argc, char **argv)
{

    int a = 1;

    if (a + 1)
    {
        goto inner_loop;
    }

    int counter = 10;
outer:

    while (counter > 0)
    {
        --counter;
    }

inner_loop:

    goto outer;

    return 0;
}