// Example generated by Mahdi Malkawi based on:
// Flow Graph Anomalies: What's in a Loop? by Michael Wolfe
// https://scholararchive.ohsu.edu/downloads/9z903022q?locale=en
// Control Flow Graph 3, (G3:) page 4

int main(int argc, char **argv)
{

    for (int counter = 0; counter < 5; ++counter)
    {
        outer:

        for (int counter2 = 0; counter2 < 5; ++counter2)
        {
        loop:
            goto loop;

        goto outer;
        }
    }

    return 0;
}