// Example generated by Mahdi Malkawi

int MAX = 100;

int main(int argc, char **argv)
{
    int counter = 0;
    int sum = 0;

    do
    {
        sum += counter;
        ++counter;
    } while (counter < MAX);

    return 0;
}