// Example generated by Mahdi Malkawi based on:
// Flow Graph Anomalies: What's in a Loop? by Michael Wolfe
// https://scholararchive.ohsu.edu/downloads/9z903022q?locale=en
// Control Flow Graph 2, (G2:) page 3

int main(int argc, char **argv)
{

    for (int counter = 0; counter < 5; ++counter)
    {
        for (int counter2 = 0; counter2 < 5; ++counter2)
        {
        loop:
            goto loop;
        }
    }

    return 0;
}